### PR TITLE
Compatibility with Ecto ~> 3.2, ULID.t, formatter

### PR DESCRIPTION
**Pull request by woylie**
I needed this to work, so I created my own fork and cherry-picked what I needed and made some changes to make it work on the CI.

- fixes compatibility issue with Ecto ~> 3.2 (cherry-picked from #7)
- adds ULID type (from #6)
- bumps Ecto requirement to `~> 3.2`
- requires Elixir 1.7 (because of newer Ecto versions)
- updates CI configuration
- formats code with mix format

### CODE REVIEW

**Comment by warmwaffles** [comment]
What is the status on this @TheRealReal?

**Comment by ykurtbas** [comment]
@woylie thank you, I am using your version, would rather not checkout a git repo though. What is the status?

**Comment by woylie** [comment]
@ykurtbas Since it doesn't seem like anything is going to happen here anymore, I just published my fork as https://hex.pm/packages/ecto_ulid_next.

**Comment by ykurtbas** [comment]
> @ykurtbas Since it doesn't seem like anything is going to happen here anymore, I just published my fork as https://hex.pm/packages/ecto_ulid_next.

Thank you! I will happily point to that and tick off one more git reference :)

**Pull request closed without merging**
